### ISSUE TITLE
missing volume units

### ISSUE THREAD

**Issue by happysalada** [putridparrot/RustUnits#1]
hey, there are a couple of missing volume units, 
cubic meters, cubic feets, oil barrel amongst others.
I would be happy to add them, would you be open to that ?

**Comment by putridparrot** [comment]
I actually have some code with cubic metres, feet, inches and oil barrel, but haven't had chance to test them fully - if you would like to add to the converters feel free - the only issue is I have all the definitions in a YAML file which I use to generate all the different language versions of the code - so I'd need to take any contributions then add to the definition file (I've not made this publicly available at the moment, not had time to clean all the code up) then regenerate the source code.

**Comment by happysalada** [comment]
I see this might create additional work for you, no problems. Im personally not in a eush, whenever you have time is fine. Thank you for the library !

**Comment by putridparrot** [comment]
Added cubic metres, cubic feet, cubic inches and oil barrels. Latest version deployed to https://crates.io/crates/unit-conversions - hopefully all works as expected.

**Comment by happysalada** [comment]
Thanks a lot !

**Comment by putridparrot** [comment]
You're welcome - let's hope my tests are spot on and I've got the formula correct :)
