### ISSUE TITLE
Add Réaumur to temperature

### ISSUE THREAD

**Issue by 0xflotus** [putridparrot/RustUnits#2]
I was considering to add Réaumur to the temperature.rs, but I saw it is auto-generated and the config file is not publicly available. So, I created this issue.

Please add `Réaumur` to your libraries to convert between the different temperature scales. 

$\text{Celsius} = \text{Réaumur} \cdot 1.25$
$\text{Réaumur} = \text{Celsius} \cdot 0.8$

$\text{Kelvin} = \text{Réaumur} \cdot 1.25 + 273.15$
$\text{Réaumur} = (\text{Kelvin} - 273.15) \cdot 0.8$

$\text{Fahrenheit} = \text{Réaumur} \cdot 2.25 + 32$
$\text{Réaumur} = \frac{\text{Fahrenheit} - 32}{2.25}$

$\text{Rankine} = \text{Réaumur} \cdot 2.25 + 491.67$
$\text{Réaumur} = \frac{\text{Rankine} - 491.67}{2.25}$

**Comment by putridparrot** [comment]
Apologies, I've only just seen this request - thanks for the information I'll have a look. Yeah this library is generated from a rather over the top YAML file, but allows me to generate code for multiple languages - I should really make the file public, it's just one of those things that started as an idea and got a bit our of hand, so all calculations are currently hard coded, anyway. I'll have a look at this new addition - thanks

**Comment by putridparrot** [comment]
Actually I've just looked at the definitions and I do have this, but commented out which suggests I wanted to test further.

**Comment by putridparrot** [comment]
Updated the code and deployed to crate.io as v 0.1.16, tests look good - whilst Rust seems to accept the accent on the name, other languages didn't so, sadly as all build through the same process I had to remove the accent. Anyway hopefully all is good, feel free to let me know if not.
